//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_5_FreelanceJobsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Bids = new HashSet<Bid>();
            this.JobRequirements = new HashSet<JobRequirement>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int EmployerId { get; set; }
        public string JobDec { get; set; }
        public string Location { get; set; }
        public double StartPrice { get; set; }
        public sbyte CanBid { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime BidEndDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<double> PaymentPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequirement> JobRequirements { get; set; }
        public virtual User User { get; set; }
    }
}
